<?php
class Installer {
    public static function envExists() {
        return file_exists(__DIR__ . '/../.env');
    }

    public static function lockExists() {
        return file_exists(__DIR__ . '/../.installed');
    }

    public static function writeEnvSafe(array $data) {
        $path = __DIR__ . '/../.env';
        $lines = [];
        $lines[] = '# Generated by installer';
        $lines[] = "APP_ENV=production";
        $lines[] = "APP_DEBUG=false";
        // ensure APP_KEY exists (persistent secret used by the app)
        $appKey = isset($data['app_key']) && $data['app_key'] ? $data['app_key'] : self::generateAppKey();
        $appKey = str_replace(["\n","\r"], '', $appKey);
        $lines[] = "APP_KEY={$appKey}";
        $lines[] = "APP_URL={$data['app_url']}";
        $lines[] = "APP_TIMEZONE={$data['app_timezone']}";
        $lines[] = "DB_TYPE={$data['db_type']}";
        $lines[] = "DB_HOST={$data['db_host']}";
        $lines[] = "DB_PORT={$data['db_port']}";
        $lines[] = "DB_NAME={$data['db_name']}";
        $lines[] = "DB_USER={$data['db_user']}";
        $lines[] = "DB_PASSWORD={$data['db_password']}";
        $lines[] = "MAIL_DRIVER={$data['mail_driver']}";
        $lines[] = "MAIL_HOST={$data['mail_host']}";
        $lines[] = "MAIL_PORT={$data['mail_port']}";
        $lines[] = "MAIL_USERNAME={$data['mail_username']}";
        $lines[] = "MAIL_PASSWORD={$data['mail_password']}";
        $lines[] = "MAIL_ENCRYPTION={$data['mail_encryption']}";
        $lines[] = "MAIL_FROM_ADDRESS={$data['mail_from_address']}";
        $lines[] = "MAIL_FROM_NAME=\"{$data['mail_from_name']}\"";
        $content = implode("\n", $lines) . "\n";
        if (file_put_contents($path, $content) === false) return false;
        @chmod($path, 0600);
        return true;
    }

    public static function generateAppKey($bytes = 32) {
        try {
            return bin2hex(random_bytes($bytes));
        } catch (Exception $e) {
            // fallback to less-preferred pseudo-random
            return bin2hex(openssl_random_pseudo_bytes($bytes));
        }
    }

    public static function testDb(array $data, &$error = null) {
        try {
            if ($data['db_type'] === 'mysql') {
                $dsn = "mysql:host={$data['db_host']};port={$data['db_port']};dbname={$data['db_name']};charset=utf8mb4";
            } else {
                $dsn = "pgsql:host={$data['db_host']};port={$data['db_port']};dbname={$data['db_name']}";
            }
            $opts = [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION];
            $pdo = new PDO($dsn, $data['db_user'], $data['db_password'], $opts);
            return $pdo;
        } catch (Exception $e) {
            $error = $e->getMessage();
            return false;
        }
    }

    public static function runSqlMigrations(PDO $pdo, $migrationsDir) {
        if (!is_dir($migrationsDir)) return [];
        $files = glob(rtrim($migrationsDir, '/') . '/*.sql');
        sort($files, SORT_NATURAL);
        $applied = [];
        foreach ($files as $f) {
            $sql = file_get_contents($f);
            if (!$sql) continue;
            try {
                $pdo->exec($sql);
                $applied[] = basename($f);
            } catch (Exception $e) {
                $applied[] = basename($f) . ' (error: ' . $e->getMessage() . ')';
            }
        }
        return $applied;
    }

    public static function importSqlFile(PDO $pdo, $filePath) {
        if (!file_exists($filePath)) return ['error'=>'file_missing'];
        $handle = fopen($filePath, 'r');
        if (!$handle) return ['error'=>'read_failed'];
        $delimiter = ';';
        $buffer = '';
        $results = [];
        while (!feof($handle)) {
            $line = fgets($handle);
            if ($line === false) break;
            $trim = trim($line);
            // handle delimiter change statements (MySQL dumps)
            if (stripos($trim, 'DELIMITER ') === 0) {
                $delimiter = substr($trim, 10);
                continue;
            }
            $buffer .= $line;
            if (self::bufferEndsWithDelimiter($buffer, $delimiter)) {
                // split out the statement up to the last delimiter occurrence
                $pos = strripos($buffer, $delimiter);
                $stmt = substr($buffer, 0, $pos);
                $buffer = substr($buffer, $pos + strlen($delimiter));
                $s = trim($stmt);
                if ($s !== '') {
                    try {
                        $pdo->exec($s);
                        $results[] = 'ok';
                    } catch (Exception $e) {
                        $results[] = 'error: ' . $e->getMessage();
                    }
                }
            }
        }
        // remaining buffer
        $remaining = trim($buffer);
        if ($remaining !== '') {
            try {
                $pdo->exec($remaining);
                $results[] = 'ok';
            } catch (Exception $e) {
                $results[] = 'error: ' . $e->getMessage();
            }
        }
        fclose($handle);
        return $results;
    }

    private static function bufferEndsWithDelimiter($buffer, $delimiter) {
        if ($delimiter === ';') {
            return (bool)preg_match('/;\s*$/', rtrim($buffer));
        }
        $dlen = strlen($delimiter);
        $trim = rtrim($buffer);
        if ($dlen === 0) return false;
        return substr($trim, -$dlen) === $delimiter;
    }

    public static function applyCloudflareRecords($apiToken, $zoneId, $records, &$out = null) {
        // records: array of ['type'=>'A','name'=>'@','content'=>'1.2.3.4','ttl'=>120,'proxied'=>false]
        $results = [];
        foreach ($records as $rec) {
            $url = "https://api.cloudflare.com/client/v4/zones/{$zoneId}/dns_records";
            $payload = json_encode($rec);
            $ch = curl_init($url);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($ch, CURLOPT_HTTPHEADER, [
                'Content-Type: application/json',
                'Authorization: Bearer ' . $apiToken
            ]);
            curl_setopt($ch, CURLOPT_POST, true);
            curl_setopt($ch, CURLOPT_POSTFIELDS, $payload);
            $resp = curl_exec($ch);
            $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
            if ($resp === false) {
                $results[] = ['ok'=>false,'http'=>$code,'error'=>curl_error($ch)];
            } else {
                $json = json_decode($resp, true);
                // extract safe evidence
                $evidence = [];
                if (isset($json['success'])) $evidence['success'] = $json['success'];
                if (isset($json['result']) && isset($json['result']['id'])) $evidence['id'] = $json['result']['id'];
                if (isset($json['errors']) && $json['errors']) $evidence['errors'] = $json['errors'];
                $results[] = ['ok'=>($code>=200 && $code<300 && ($json['success']??false)),'http'=>$code,'evidence'=>$evidence];
            }
            curl_close($ch);
        }
        $out = $results;
        return $results;
    }

    public static function createAdmin(PDO $pdo, $email, $name, $password) {
        $hash = password_hash($password, PASSWORD_DEFAULT);
        try {
            $pdo->exec("CREATE TABLE IF NOT EXISTS users (id SERIAL PRIMARY KEY, name VARCHAR(255), email VARCHAR(255) UNIQUE, password VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
            $stmt = $pdo->prepare('INSERT INTO users (name,email,password) VALUES (:name,:email,:password)');
            $stmt->execute([':name'=>$name, ':email'=>$email, ':password'=>$hash]);
            return true;
        } catch (Exception $e) {
            return $e->getMessage();
        }
    }

    public static function createLock() {
        $path = __DIR__ . '/../.installed';
        $content = "installed=" . date('c') . "\n";
        file_put_contents($path, $content);
        @chmod($path, 0600);
    }
}

?>
